### ISSUE TITLE
Documentation is missing 'classes' prop

### ISSUE THREAD

**Issue by techfoundrynz** [alexplumb/material-ui-banner#2]
An object containing additional classNames to be applied to the various components of the panel can be passed through to the banner component to enable additional styling. Adding this to the docs would be helpful for people looking to implement this component.

**Comment by alexplumb** [comment]
The `classes` prop only exists because it's using `withStyles` from material-ui and shouldn't be overwritten. I've added support for `paperProps` and `cardProps` properties that can be passed in, however, and you should be able to pass `className` in as a property, or anything else you want, in order to customize the look and feel of the banner a little better.

Perhaps in the future I'll add support for passing `classes` as a property to the component, but until then I won't be adding documentation for it.
